In [12]:
import numpy as np
import pandas as pd
from sklearn import preprocessing


In [13]:
data_train=pd.read_csv("steam_train.csv")

In [14]:
data_test=pd.read_csv("steam_test.csv")

In [15]:
data_train.head()

appid                                             name release_date  \
0  708830                             The Armament Project   2017-09-28   
1  538000  Hop Step Sing! Kisekiteki Shining! (HQ Edition)   2017-06-29   
2  603530                             A Robot Named Fight!   2017-09-07   
3  564040                                     ZANGEKI WARP   2017-02-15   
4  951940                     Almost There: The Platformer   2019-02-19   

   english                              developer  \
0        1                                 DysTop   
1        1  Kodansha;Polygon Pictures Inc.;Lantis   
2        1                      Matt Bitner Games   
3        1                             ASTRO PORT   
4        1                            Bony Yousuf   

                           publisher          platforms  required_age  \
0                             DysTop            windows             0   
1                             Degica            windows             0   
2                  Matt Bitner Games  windows;mac;linux             0   
3                          Nyu Media      windows;linux             0   
4  The Quantum Astrophysicists Guild  windows;mac;linux             0   

                                          categories  \
0           Single-player;Partial Controller Support   
1           Single-player;Partial Controller Support   
2  Single-player;Local Co-op;Shared/Split Screen;...   
3  Single-player;Steam Achievements;Steam Trading...   
4  Single-player;Steam Achievements;Full controll...   

                         genres              steamspy_tags  achievements  \
0                  Action;Indie         Action;Indie;Space             0   
1                        Casual            Casual;VR;Anime             0   
2     Violent;Gore;Action;Indie  Action;Metroidvania;Indie            60   
3                  Action;Indie  Action;Indie;Shoot 'Em Up            53   
4  Action;Casual;Indie;Strategy        Indie;Action;Casual            24   

   positive_ratings  negative_ratings  average_playtime  median_playtime  \
0                 2                 2                 0                0   
1                30                 4                 0                0   
2               271                30               279              279   
3                16                 0                 0                0   
4                29                 1                 0                0   

        owners  price  
0      0-20000   2.89  
1      0-20000   3.99  
2  20000-50000  10.29  
3      0-20000   4.79  
4      0-20000   7.19

In [16]:
X=data_train[['appid','english','achievements','positive_ratings','negative_ratings','average_playtime','median_playtime']].values
Y=data_train['price'].values
X1=data_test[['appid','english','achievements','positive_ratings','negative_ratings','average_playtime','median_playtime']].values

Multiple Linear Regression

In [17]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
#x = np.asanyarray(train[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_COMB']])
#y = np.asanyarray(train[['CO2EMISSIONS']])
regr.fit (X, Y)
# The coefficients
print ('Coefficients: ', regr.coef_)
print("Intercept: ",regr.intercept_)

Coefficients:  [-4.69902736e-06 -4.05160532e-01 -6.88794912e-05 -8.60777798e-06
  9.49243866e-05  1.36697869e-04  2.11437207e-05]
Intercept:  9.221453109743013


In [18]:
yhat=regr.predict(X1)

In [27]:
yhat[0:5]

array([6.39781784, 4.07152557, 7.5621242 , 7.83489813, 5.11036339])

In [29]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model

poly = PolynomialFeatures(degree=2)
train_x_poly = poly.fit_transform(X)
train_x_poly

array([[1.0000e+00, 7.0883e+05, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.0000e+00, 5.3800e+05, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.0000e+00, 6.0353e+05, 1.0000e+00, ..., 7.7841e+04, 7.7841e+04,
        7.7841e+04],
       ...,
       [1.0000e+00, 4.6540e+04, 1.0000e+00, ..., 2.0164e+04, 2.2294e+04,
        2.4649e+04],
       [1.0000e+00, 6.7165e+05, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.0000e+00, 9.0027e+05, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])

In [40]:
clf = linear_model.LinearRegression()
train_y = clf.fit(train_x_poly, Y)

test_x_poly = poly.fit_transform(X1)
yhat = clf.predict(test_x_poly)
yhat

array([6.26390619, 4.01129479, 7.40534346, ..., 5.48292481, 6.7386407 ,
       4.26686213])

In [42]:
#Non Linear Regression Analysis

In [41]:
#Modelling

x_id=data_test["appid"].values
df=pd.DataFrame({'appid':x_id,'price':yhat})
df['price']=df['price'].astype(float)
df['appid']=df['appid'].astype(int)
df.to_csv('Sub5.csv',index=False)